// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyjqjeosooqqpuvceyqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5anFqZW9zb29xcXB1dmNleXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MzY2MjIsImV4cCI6MjA4MjUxMjYyMn0.W82JVX4-2ZdxU6WgjiQqE634dYqlBvHvXNuWzYOXmyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});